# Generated by Django 5.2.4 on 2025-09-11 11:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryimage',
            old_name='title',
            new_name='event',
        ),
        migrations.AddField(
            model_name='announcement',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='announcements/pdfs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
