# Generated by Django 5.2.6 on 2025-09-19 10:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('e_transfer_id', models.CharField(max_length=120)),
                ('adults', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('children', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('registration_type', models.CharField(choices=[('Individual', 'Individual'), ('Family', 'Family'), ('Student', 'Student')], max_length=16)),
                ('consent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
